package com.khipu

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.module.annotations.ReactModule

/**
 * Module declaration for the new architecture.
 *
 * `NativeKhipuSpec` is generated by codegen and only exists when build.gradle
 * applies the React plugin, hence this source set. Logic lives in
 * [KhipuModuleImpl]; `getName()` comes from the generated superclass.
 */
@ReactModule(name = KhipuModuleImpl.NAME)
class KhipuModule(reactContext: ReactApplicationContext) : NativeKhipuSpec(reactContext) {

  private val impl = KhipuModuleImpl(reactContext)

  override fun startOperation(operationOptions: ReadableMap, promise: Promise) {
    impl.startOperation(operationOptions, promise)
  }
}
