source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'
# La plantilla fija concurrent-ruby < 1.3.4 porque las versiones nuevas ya no
# hacen require 'logger', y activesupport 6.1.7.10 y 7.0.8.7 dependian de eso
# (medido: 7.0.8.7 + concurrent-ruby 1.3.8 da NameError en
# LoggerThreadSafeLevel). 7.0.10, 7.1.5.2, 7.1.6 y 7.2.4 lo hacen
# solas, y el Gemfile.lock resuelve 7.2.4: el pin solo dejaba concurrent-ruby
# vulnerable.

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
